export const UserData = {
  firstName: "",
  lastName: "",
  currentAge: 18,
  retirementAge: 0,
  monthlyIncome: 0,
  monthlyExpenses: 0,
  housing: 0,
  utilities: 0,
  transportation: 0,
  food: 0,
  debtRepayment: 0,
  insurance: 0,
  health: 0,
  entertainment: 0,
  education: 0,
  investments: 0,
  familyExpenses: 0,
  other: 0,
}